[solution]
name = "cong-dsa-mixed"      # Solution name
definition = "dsa_sparse_attention_h16_ckv512_kpe64_topk2048_ps64"  # Track definition
author = "Cong"                   # Team/author name

[build]
#language = "cuda"                 # triton | cuda
#entry_point = "kernel4.cu::kernel"     
language = "triton"               # triton | cuda
entry_point = "kernel5.py::run"           
